//! Boundary harness — `nmemory-mcp-params-json`, declared in `tools/gates/registry.toml`.
//!
//! THE BOUNDARY. Every MCP `tools/call` arrives as JSON-RPC params and is
//! deserialized into a typed `*Params` struct before any handler runs. That
//! deserialization IS the trust boundary of the server: after it, the code
//! assumes a well-formed request.
//!
//! WHY `IngestParams` SPECIFICALLY. Most params types are derived
//! `#[derive(Deserialize)]`, where serde owns the parsing and a defect would be
//! upstream. `IngestParams` is the exception — it carries a HAND-WRITTEN
//! `Deserialize` impl (`src/server.rs`) because it accepts either a single item
//! or a `{"items":[...]}` batch and produces a contract-shaped error message
//! naming the offending field. Hand-written deserialization is code this
//! repository owns, it runs before any validation, and it is reached by anything
//! that can speak to the server.
//!
//! WHAT IS ASSERTED. That a verdict is reached. Nearly every generated input is
//! invalid and REJECTION is the correct answer, so requiring success would
//! assert the opposite of the contract. The failure this hunts is the one the
//! error-message machinery invites: the impl inspects the raw `serde_json::Value`
//! to describe what was wrong, and inspecting a value the shape of which was
//! never checked is where an index or an unwrap goes wrong on data a caller
//! chose.

use bolero::check;
use nmemory::server::{IngestItemParams, IngestParams};

#[test]
fn ingest_params_reach_a_verdict() {
    check!().with_max_len(4096).for_each(|bytes: &[u8]| {
        // The hand-written impl, including the single-vs-batch discrimination
        // and the field-naming error path it runs on failure.
        let parsed = serde_json::from_slice::<IngestParams>(bytes);

        // THE ROUTING LAW, checked rather than assumed. The impl documents
        // manual routing "on the presence of `items`", and it exists because the
        // untagged derive it replaced parsed a MIXED payload as Batch and
        // SILENTLY DROPPED the top-level capture fields. Silent dropping is data
        // loss no panic-freedom assertion can see — and asserting only that the
        // parse returns killed nothing when this harness was first measured.
        if let Ok(params) = &parsed {
            let carries_items = serde_json::from_slice::<serde_json::Value>(bytes)
                .ok()
                .and_then(|value| value.get("items").cloned())
                .is_some();
            match params {
                IngestParams::Batch { .. } => assert!(
                    carries_items,
                    "a document with NO `items` key routed to the Batch arm, so its \
                     top-level capture fields were dropped"
                ),
                IngestParams::Single(_) => assert!(
                    !carries_items,
                    "a document CARRYING `items` routed to the Single arm, so every \
                     batched item was dropped"
                ),
            }
        }

        // The derived sibling, deserialized from the same bytes. It carries
        // `deny_unknown_fields`, so it exercises serde's rejection path
        // rather than the crate's — cheap, and it keeps the two in step:
        // if the hand-written impl ever accepts a shape the derived one
        // rejects, that divergence is reachable from here.
        let _ = serde_json::from_slice::<IngestItemParams>(bytes);

        // TWO KNOWN-GOOD DOCUMENTS, ROUTED EVERY ITERATION. The negative checks
        // above only run when the generated bytes happen to parse, so a mutation
        // that makes the router REJECT more never reaches them — and that is the
        // realistic break: `delete !` in `if !is_batch` sends every valid single
        // document down the batch path, where its own fields become "stray" and
        // the whole capture is refused. Measured: without these two, this harness
        // killed nothing.
        let single = br#"{"content":"a fact","source":"s","anchor":"a.md:1"}"#;
        match serde_json::from_slice::<IngestParams>(single) {
            Ok(IngestParams::Single(_)) => {}
            Ok(IngestParams::Batch { .. }) => {
                panic!("a document with NO `items` routed to the Batch arm")
            }
            Err(error) => panic!("a valid SINGLE capture was refused: {error}"),
        }

        let batch = br#"{"items":[{"content":"a","source":"s","anchor":"x"},{"content":"b","source":"s","anchor":"y"}]}"#;
        match serde_json::from_slice::<IngestParams>(batch) {
            Ok(IngestParams::Batch { items }) => assert_eq!(
                items.len(),
                2,
                "a two-item batch arrived carrying {} item(s)",
                items.len()
            ),
            Ok(IngestParams::Single(_)) => {
                panic!("a document CARRYING `items` routed to the Single arm")
            }
            Err(error) => panic!("a valid BATCH capture was refused: {error}"),
        }
    });
}
