//! Boundary harness — `nmemory-bridge-markdown`, declared in `tools/gates/registry.toml`.
//!
//! THE BOUNDARY. [`nmemory::bridge::read_source`] reads `CLAUDE.md`,
//! `AGENTS.md`, and every `.md` in a memory directory — files written by other
//! tools, by other agents, and by hand. The crate's own module documentation
//! treats them as tainted: corroboration travels with the bytes, never with
//! trust in whatever produced them.
//!
//! WHY THROUGH A FILE AND NOT THE PARSER DIRECTLY. The markdown splitter
//! (`split_document`, `heading_level`, `body_start`, `is_fence_marker`) is
//! private, so a harness in `tests/` cannot name it. Writing the generated bytes
//! to a real file and calling the public reader is the honest way in: it costs
//! one file write per iteration, and it exercises the reader's own decode and
//! anchor construction as well as the splitter. Promoting the private functions
//! to `pub` to make the harness cheaper would widen the crate's API for the
//! benefit of a test, which is the wrong trade.
//!
//! WHAT IS ASSERTED. That the reader reaches a verdict on arbitrary bytes — a
//! heading with no body, an unterminated code fence, a file that is one NUL, a
//! multi-byte character split across what the splitter thinks is a line
//! boundary. `read_source` returns `Result`, so a malformed document has a
//! correct answer available to it and a panic is never one of them.

use std::path::Path;

use bolero::check;
use nmemory::bridge::{BridgeSource, read_source};

/// A scratch directory that removes itself, so a run of thousands of iterations
/// does not leave thousands of trees behind. `tempfile` is already a dependency
/// of this crate, so this costs nothing new.
fn write_document(dir: &Path, name: &str, bytes: &[u8]) -> std::io::Result<()> {
    std::fs::write(dir.join(name), bytes)
}

#[test]
fn bridge_reads_any_markdown_without_panicking() {
    check!().with_max_len(4096).for_each(|bytes: &[u8]| {
        let Ok(scratch) = tempfile::tempdir() else {
            // A machine that cannot make a temp dir cannot run this
            // property. Skipping is honest; asserting would report a
            // filesystem failure as a parser defect.
            return;
        };
        let base = scratch.path();

        // Both project-level sources in one iteration: they share the
        // splitter, and writing two files costs one syscall more than
        // writing one.
        if write_document(base, "CLAUDE.md", bytes).is_err()
            || write_document(base, "AGENTS.md", bytes).is_err()
        {
            return;
        }

        // The anchor root is the same directory, which is the shape the boot
        // path uses when the project IS the anchor root.
        let _ = read_source(&BridgeSource::ProjectClaudeMd, base, base);
        let _ = read_source(&BridgeSource::ProjectAgentsMd, base, base);

        // The memory-directory source walks the directory rather than
        // probing one name, so it exercises the sorted-name ordering as
        // well as the splitter.
        if write_document(base, "note.md", bytes).is_ok() {
            let _ = read_source(&BridgeSource::MemoryDir(base.to_path_buf()), base, base);
        }

        // THE MONOTONICITY PROPERTY, and the one with teeth. A document that
        // OPENS with a real section keeps producing that section no matter what
        // arbitrary bytes follow it. Asserting only "does not panic" killed
        // nothing when this harness was measured, because a reader mutated to
        // return an empty list does not panic — it silently forgets every
        // CLAUDE.md the boot path was supposed to import, and the import reports
        // success with nothing in it.
        let mut prefixed = Vec::from(
            b"# Known Section\n\nA sentence the splitter must keep returning.\n\n".as_slice(),
        );
        prefixed.extend_from_slice(bytes);
        if write_document(base, "CLAUDE.md", &prefixed).is_err() {
            return;
        }
        if let Ok(candidates) = read_source(&BridgeSource::ProjectClaudeMd, base, base) {
            assert!(
                !candidates.is_empty(),
                "a document OPENING with a real section produced NO candidates, so \
                 appending arbitrary bytes erased content the reader had already found"
            );
            for candidate in &candidates {
                assert!(
                    !candidate.content.trim().is_empty(),
                    "a candidate came back with blank content"
                );
                assert!(
                    !candidate.anchor.trim().is_empty(),
                    "a candidate came back with a blank anchor, so its provenance cannot \
                     be resolved back to a file"
                );
                assert!(
                    !candidate.source_label.trim().is_empty(),
                    "a candidate came back with a blank source label"
                );
            }
        }
    });
}
